
MODEL:
  META_ARCHITECTURE: "fcn8s"

  BACKBONE:
    PRETRAINED: True
    WEIGHT: '/mnt/truenas/scratch/xingyu.liao/model_zoo/vgg16-397923af.pth'

  REFINEMENT:
    NAME: ''

DATASETS:
  ROOT: '/mnt/truenas/scratch/xingyu.liao/DATA/VOCdevkit/VOC2012'

SOLVER:
  MAX_EPOCHS: 13
  CHECKPOINT_PERIOD: 13

OUTPUT_DIR: "/mnt/truenas/scratch/xingyu.liao/checkpoints/train_fcn8s_atonce"
