MODEL:
  META_ARCHITECTURE: "fcn16s"

  BACKBONE:
    PRETRAINED: False

  REFINEMENT:
    NAME: 'fcn32s'
    WEIGHT: "/mnt/truenas/scratch/xingyu.liao/checkpoints/train_fcn32s/fcn_model_13.pth"

DATASETS:
  ROOT: '/mnt/truenas/scratch/xingyu.liao/DATA/VOCdevkit/VOC2012'

SOLVER:
  MAX_EPOCHS: 8
  CHECKPOINT_PERIOD: 8

OUTPUT_DIR: "/mnt/truenas/scratch/xingyu.liao/checkpoints/train_fcn16s"
